apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: danila-nikonov-1304
type: Opaque
stringData:
  POSTGRES_DB: dev
  POSTGRES_USER: backend
  POSTGRES_PASSWORD: backend
  REDIS_PASSWORD: backend
